### ISSUE TITLE
Strange behavior using touch pad

### ISSUE THREAD

**Issue by alejandrogiubel** [mayurnile/web_smooth_scroll#1]
Strange behavior using touch pad. It works fine using the mouse, but when using the touchpad the scroll behavior becomes weird and unstable

**Comment by mayurnile** [comment]
Can you please tell which device you are using ?

**Comment by alejandrogiubel** [comment]
Mac book pro, Bi Sur 11.1

**Comment by mayurnile** [comment]
I tested on my Mac book pro - Monterey 12.3.1, it's working fine and also tested on Asus Vivbook, Lenovo and Dell laptops with their touchpad no issues over there. Still can you share any screen recording what strange you are feeling while scrolling ?

**Comment by xelarich** [comment]
I've same problem on my Mac book pro macOS ventura
```
body: WebSmoothScroll(
        controller: _scrollController,
        child: SingleChildScrollView(
          physics: const NeverScrollableScrollPhysics(),
          controller: _scrollController,
          child: Column(
```

try to look this 
https://drive.google.com/file/d/1tjzGC06ubsEA6mtR4mk2_vHE36Sadea1/view?usp=sharing
