### ISSUE TITLE
Disables Scrolling With Drag Gesture (Touch)

### ISSUE THREAD

**Issue by JaffaKetchup** [mayurnile/web_smooth_scroll#2]
Hi, and thanks for this great package.

I've got it setup and working just right for mouse/wheel, but unfortunately, the widget has completely disabled scrolling on mobile, where the drag gesture is used. Not sure if this is intended functionality and a 'won't fix' situation, or if this is indeed my fault or a bug.

I'm happy to provide some code if you need it, and you can see the effect over at https://jaffaketchup.dev/.

Looking forward to hearing from you :)

**Comment by mayurnile** [comment]
Hi @JaffaKetchup , the plugin is intentionally made to not allow scrolling via touch it is to be used only by mouse scroll wheel. For that you can have a workaround. You can add a check if the platform is web then use this plugin else you can render your widgets in a normal listview.

**Comment by JaffaKetchup** [comment]
Thanks for the quick response. However, web works on both desktop and mobile, so just doing a platform check won't differentiate between these two.

**Comment by mayurnile** [comment]
You can check device width, that's the same logic I'm using in my own portfolio.
Here is the code:
https://github.com/mayurnile/mayurnile_portfolio/blob/main/lib/presentation/landing_screen/landing_screen.dart

**Comment by JaffaKetchup** [comment]
That's not really a reliable solution. What about laptops with touchscreen, where the user is using the touchscreen? Large tablets might not work, and equally, small monitors would disable this library's functionality.

I understand if you can't fix this, but width-based decisions are not a reliable enough workaround in this case.

**Comment by mayurnile** [comment]
Yeah width based is a very temporal solution but we cannot detect which device is being used to scroll, and we are relied only on the mouse scroll tickers we get and the scrolling issue is only with the mouse wheel and trackpads. That's the primary focus to resolve this issue until the Flutter team comes up with a solution.

**Comment by ijasmv** [comment]
Scrolling on macbook with touchpad is smooth like mobile device. So we need to check whether scrolling is with touchpad or mouse for using the package.

**Comment by mhmzdev** [comment]
Facing the same issue
The package put the web app to a lot of janks/hangs when scroll using touchpad on laptop/macbook

Would love to have this thing here.

**Comment by mayurnile** [comment]
Sorry for delayed response @ijasmv @mhmzdev ,
I've tried to fix the scrolling on touchpad will keeping the smooth animations intact, you can check that out in the latest v1.1.0
